### PR TITLE
add funcs and types to APE

### PR DESCRIPTION
**Pull request by lufia**
I'm trying to add some funcs and types to port major Unix'ish libraries.

### funcs

- inet_ntop
- arc4random
- arc4random_buf
- getentropy
- fchdir
- poll
- clock_gettime
- clock_settime
- getaddrinfo
- freeaddrinfo
- getnameinfo
- gai_strerror

### types

- s{8,16,32,64}
- u{8,16,32,64}
- u{8,16,32,64}int
- u_int{8,16,32,64}_t
- socklen_t
- clockid_t

### others

- stdbool.h
- PRI?{8,16,32,64}

### CODE REVIEW

**Comment by 0intro** [comment]
You may be interested by looking to the old [ape-erik](http://9legacy.org/9legacy/patch/ape-erik.diff) patch from Erik Quanstrom, which implements some new functions to APE. That was required to run Python 2.7 on Plan 9.

**Comment by lufia** [comment]
@0intro Thank you very much. I'm looking the patch.

**Comment by lufia** [comment]
@0intro 
I've ported *zlib*, *libexpat*, *LibreSSL portable*, and *curl* with #7, *git* may soon.
Could you accept these patches?
curl

**Comment by 0intro** [comment]
It looks very interesting. Thanks! I'll review your patches.

**Comment by lufia** [comment]
I added two commits.

**Comment by lufia** [comment]
@0intro This p-r is completed because `git` works. I don't add patches to this p-r since now.
If you think had better to clean commit logs, please mention to me.

**Comment by lufia** [comment]
@0intro Is there any updates on this?

**Comment by sstallion** [comment]
@lufia I have a little time to take a look at the patches. Did you ever get a chance to rebase this based on the `ape-erik` patch? I have this applied to my local systems and would be happy to test this out if you have rebased.

**Comment by lufia** [comment]
@sstallion ok.  Though it will take a little time I will try to rebase my patch onto ape-erik.diff.

**Comment by sstallion** [comment]
Excellent. Thanks!

**Comment by lufia** [comment]
@sstallion I'm sorry for late work.

I've put the patch that is rebased on **ape-erik.diff** at https://patch-diff.githubusercontent.com/raw/lufia/plan9/pull/5.diff (ref lufia/plan9#5). I checked to be able to compile all sources under **/sys/src/ape**, but don't check to compile git yet.

**Comment by sstallion** [comment]
No apologies needed - thanks for the hard work! I should have some time
this weekend to try applying the patch and seeing if I can get things to
compile on my side. Thanks again!

**Pull request closed without merging**
